# Long-term Sovereign Credit Ratings EDA

In [1]:
import pandas as pd
import numpy as np

In [38]:
ratings_df = pd.read_csv('data/country_ratings2.csv')
ratings_df.head(10)

   Unnamed: 0        date        country          rating  agency
0           0  2018-04-25  United States    Aaa (Stable)  moodys
1           1  2013-07-18  United States    Aaa (Stable)  moodys
2           2  2011-08-02  United States  Aaa (Negative)  moodys
3           3  2011-07-13  United States  (Under Review)  moodys
4           4  2003-11-15  United States        (Stable)  moodys
5           5  1949-02-05  United States             Aaa  moodys
6           6  2013-06-10  United States        (Stable)      sp
7           7  2011-08-05  United States  AA+ (Negative)      sp
8           8  2019-04-02  United States             AAA   fitch
9           9  2018-04-05  United States    AAA (Stable)   fitch

In [33]:
ratings_df.rating.unique()

array(['Aaa (Stable)', 'Aaa (Negative)', '(Under Review)', '(Stable)',
       'Aaa', 'AA+ (Negative)', 'AAA', 'AAA (Stable)', 'AAA (Negative)',
       'Aa2 (Stable)', 'Aa1 (Negative)', 'Aa1 (Stable)', '(Negative)',
       'AA (Negative)', 'AA', 'AA+ (Stable)', 'AA+', 'Aa2 (Positive)',
       'Aa1', 'AA (Stable)', 'RAT-S&P-LO', 'A1 (Stable)', 'Aa3 (Stable)',
       'Aa2', '(Positive)', 'A+ (Stable)', 'AA-', 'A', 'A (Stable)',
       'A (Negative)', 'A+', 'A+ (Negative)', 'Baa1 (Stable)',
       'Baa2 (Stable)', 'Baa2 (Positive)', 'Baa3 (Stable)',
       'Baa3 (Negative)', 'Baa3 (Under Review)', 'A3', 'A1 (Negative)',
       'Aa2 (Negative)', 'A- (Positive)', 'BBB+ (Stable)', 'BBB (Stable)',
       'BBB- (Negative)', 'BBB+ (Negative)', 'AA- (Negative)', 'A-',
       'A- (Stable)', 'BBB+ (Positive)', 'BBB+', 'BBB (Negative)',
       'Baa2 (Under Review)', 'Baa2 (Negative)', 'Baa2', 'A2 (Negative)',
       'P-1', 'Aa3', 'A1', 'BBB- (Stable)', 'BBB', 'A- (Negative)',
       'AA- (Stable)', 'Baa3 (Positive)', 'Ba1 (Positive)',
       'Ba1 (Stable)', 'Ba2 (Under Review)', 'NP', 'Ba3 (Negative)',
       'Ba3', 'Ba2 (Negative)', 'Baa1 (Under Review)', 'A3 (Negative)',
       'BB+ (Stable)', 'BB (Negative)', 'BB+ (Positive)', 'BB+',
       'BB+ (Negative)', 'B1 (Stable)', 'B3 (Positive)',
       'Caa2 (Positive)', 'Caa3 (Stable)', 'Caa3 (Under Review)',
       'Caa2 (Negative)', 'Caa1 (Stable)', 'C', 'Ca', 'Caa1 (Negative)',
       'B1 (Negative)', 'A3 (Under Review)', 'A2', 'Baa1', 'Baa3',
       'BB- (Positive)', 'B+ (Stable)', 'B (Positive)', 'B- (Stable)',
       'CCC+ (Stable)', 'CCC- (Negative)', 'CCC (Negative)',
       'CCC+ (Negative)', 'B-', 'B (Stable)', 'SD', 'CCC (Stable)',
       'CC (Negative)', 'BB-', 'BB- (Stable)', 'B- (Positive)', 'CCC',
       'CC', 'RD', 'B+ (Negative)', 'A (Positive)', 'BBB (Positive)',
       'BBB-', 'A2 (Stable)', 'A3 (Positive)', 'Baa1 (Positive)',
       'Ba1 (Negative)', 'Ba1', 'Baa1 (Negative)', 'Aa2 (Under Review)',
       'B (Negative)', 'Ba3 (Stable)', 'B1 (Positive)', 'Ba2',
       'Ba2 (Stable)', 'B+', 'B+ (Positive)', 'B3 (Stable)',
       'B2 (Under Review)', 'B2 (Stable)', 'B', 'Caa2 (Under Review)',
       'B2 (Negative)', 'Caa1 (Positive)', 'B3', 'Caa1', 'Caa3', 'B2',
       'B1', 'B- (Negative)', 'BB (Stable)', 'DDD', 'D', 'C (Negative)',
       'BB- (Negative)', 'BB', 'AA+ (Positive)', 'Ba1 (Under Review)',
       'BBB- (Positive)', 'B3 (Under Review)', 'B3 (Negative)',
       'Aa3 (Negative)', 'BB (Positive)', 'A3 (Stable)', 'NR',
       'Caa2 (Stable)', 'Caa1 (Under Review)', 'Aa', 'A1 (Positive)',
       'Aa3 (Positive)', 'Ba2 (Positive)', 'Ba3 (Positive)',
       'Caa3 (Positive)', 'Caa3 (Negative)', 'Ba3 (Under Review)', 'CCC+',
       'A+ (Positive)', 'Caa2', 'CCC+ (Positive)', 'Aa1 (Positive)',
       'AA- (Positive)', 'B2 (Positive)', 'RD (Positive)', '(P)B1', 'WR',
       'DD (Positive)', 'DD (Stable)', 'A2 (Positive)', 'CCC (Positive)',
       'Baa', 'B1 (Under Review)', 'Aa3 (Under Review)', 'AA (Positive)',
       'CCC-', 'P-2', 'Ca (Negative)', 'B2 ()', 'C (Stable)', 'WD'],
      dtype=object)

In [30]:
valid_ratings=pd.read_csv('data/creditratingtable.csv')
valid_ratings

                                           Grade Moodys    SP Fitch
0                                          Prime    Aaa   AAA   AAA
1                                     High Grade    Aa1   AA+   AA+
2                             Upper medium grade    Aa2    AA    AA
3                             Upper medium grade    Aa3   AA-   AA-
4                             Upper medium grade     A1    A+    A+
5                             Upper medium grade     A2     A     A
6                             Upper medium grade     A3    A-    A-
7                             Lower medium grade   Baa1  BBB+  BBB+
8                             Lower medium grade   Baa2   BBB   BBB
9                             Lower medium grade   Baa3  BBB-  BBB-
10              Non-investment grade speculative    Ba1   BB+   BB+
11              Non-investment grade speculative    Ba2    BB    BB
12              Non-investment grade speculative    Ba3   BB-   BB-
13                            Highly speculative     B1    B+    B+
14                            Highly speculative     B2     B     B
15                            Highly speculative     B3    B-    B-
16                             Substantial risks   Caa1  CCC+  CCC+
17                             Substantial risks   Caa2   CCC   CCC
18                             Substantial risks   Caa3  CCC-  CCC-
19                         Extremely speculative     Ca    CC    CC
20                         Extremely speculative    NaN   NaN     C
21  In default with little prospect for recovery    NaN    SD    RD
22                                    In default      C     D     D
23                                    In default    NaN   NaN    DD
24                                    In default    NaN   NaN   DDD
25                                     Not rated     WR    NR   NaN

In [31]:
moodys_ratings = list(valid_ratings.Moodys.dropna())
sp_ratings = list(valid_ratings.SP.dropna())
fitch_ratings = list(valid_ratings.Fitch.dropna())